### ISSUE TITLE
EUIDLOOKUP error

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [xthursdayx/ferdi-server-docker#4]
Hi guys,

Unfortunately I can't get the Docker container to run, I started it without specifying a user. Also tried to create and specify another user but that gives me other errors...

```
**** Installing AdonisJS and deps ****

npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
/usr/bin/adonis -> /usr/lib/node_modules/@adonisjs/cli/index.js

> nodemon@1.19.3 postinstall /usr/lib/node_modules/@adonisjs/cli/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@adonisjs/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EUIDLOOKUP
npm ERR! lifecycle could not get uid/gid
npm ERR! lifecycle [ 'nobody', 0 ]
npm ERR! lifecycle
npm ERR!
npm ERR! Failed to look up the user/group for running scripts.
npm ERR!
npm ERR! Try again with a different --user or --group settings, or
npm ERR! run with --unsafe-perm to execute scripts as root.

npm ERR! A complete log of this run can be found in:
```

Hope you can help me :)

**Comment by xthursdayx** [comment]
The NPM WARN messages are nothing to worry about. 

I'm not sure why you're seeing this EUIDLOOKUP error, I have built this image in a number of different environments and haven't had that issue. Can you share the docker run command you're using?

**Comment by xthursdayx** [comment]
@vantezzen I don't want to take this off the original topic, but do you have any ideas about the NPM WARN errors? I've noticed these consistently since I first started working on this docker image. Are they a result of the Dockerfile installing a later version of NPM than the one used to create the AdonisJS app? 

At one point with an earlier version of this image I considered repackaging all of the app code as part of the image (instead of curling the most recent version from Github on run) and tried running `npm audit` to try to identify and fix these "vulnerabilities" with the kleur and set-value modules and update the package.json without breaking other dependencies. If I recall correctly I was able to sort this out, but ended up choosing to go with the option to pull updated code from the getferdi/server repo instead.

**Comment by xthursdayx** [comment]
@h3x4d3c1m4l  I think that your issue is probably unrelated, but based on the docker compose snippet that you shared in the other issue you opened it appears that you did not start your container with any of the database ENV variables or the NODE_ENV variable. Can you try running it again with these?

```
-e NODE_ENV=development \
  -e DB_CONNECTION=<database> \
  -e DB_HOST=<yourdbhost> \
  -e DB_PORT=<yourdbPORT> \
  -e DB_USER=<yourdbuser> \
  -e DB_PASSWORD=<yourdbpass> \
  -e DB_DATABASE=<yourdbdatabase> \
```

**Comment by vantezzen** [comment]
The NPM warnings should be nothing to worry about as kleur and set-value are only used by AdonisJS's CLI which does not expose any vulnerabilities to your server.

**Comment by xthursdayx** [comment]
Cool, thanks for clarifying. That's what I assumed, but it's good to have that confirmed.

**Comment by h3x4d3c1m4l** [comment]
Added the `NODE_ENV=development` and `DB_CONNECTION=sqlite`, now after the errors it starts to initialize the sqlite db it seems. There seems to be more issues though :(

There is probably an error in the invocation of `nc` somewhere as it keeps spamming the `busybox nc` help, also some commend named `adonis` not found:

```
Usage: nc [OPTIONS] HOST PORT  - connect
nc [OPTIONS] -l -p PORT [HOST] [PORT]  - listen

	-e PROG	Run PROG after connect (must be last)
	-l	Listen mode, for inbound connects
	-lk	With -e, provides persistent server
	-p PORT	Local port
	-s ADDR	Local address
	-w SEC	Timeout for connects and final net reads
	-i SEC	Delay interval for lines sent
	-n	Don't do DNS resolution
	-u	UDP mode
	-v	Verbose
	-o FILE	Hex dump traffic
	-z	Zero-I/O mode (scanning)

**** Run DB migration ****
/var/run/s6/etc/cont-init.d/50-config: line 125: adonis: command not found
```

**Comment by h3x4d3c1m4l** [comment]
Whole log: https://pastebin.com/bBsL2JV8

**Comment by xthursdayx** [comment]
@h3x4d3c1m4l thanks sticking with this. The nc command in the cont-init.d script was failing because you did not include the env variables <db_host> or <db_port> in your `docker compose`. I'm not sure how exactly this relates to the UID/GID issue, but it seems likely that they are related.

The way that I originally wrote the cont-init.d script assumed that the user would include ALL of the available ENV variables in their `docker run` command (or docker-compose.yml). I have fixed this now so that the default ENV variable options will be used if they are not input or changed by the user. 

Could you please pull the latest version of this image, delete your persistent folder and try building and running the container again?

Thanks.

**Comment by h3x4d3c1m4l** [comment]
I have tried, but the container still does not keep running:

https://pastebin.com/V1DXisYL

Any reason you have not specified a CMD in de Dockerfile? Because now it will try to run the whole Dockerfile script everytime I start te container, while it really only has to run al those tasks once (only when building the container).

**Comment by xthursdayx** [comment]
I have to apologize @h3x4d3c1m4l , no matter what I have tried I've been unable to reproduce your issue. When you tried running this container again, did you delete the existing container, image and the persistent folder from your computer? **If not, please make sure to do this when trying again.** If you did do this and it still failed, could you please clearly describe your whole process of running this container? Are you still using docker-compose? 

Can I ask you to try to create and run the container using the following command, after replacing <yourferdidirectory>, <yourferdidatabasedirectory>, <yourferdirecipedirectory> and  with the correct directory locations: 
```
docker run --name='ferdi-server' -e NODE_ENV=development -e DB_CONNECTION=sqlite -e DB_HOST=127.0.0.1 -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD= -e DB_DATABASE=adonis -e IS_CREATION_ENABLED=true -e CONNECT_WITH_FRANZ=true -p '3333:80' -v <yourferdidirectory>:/config -v <yourferdidatabasedirectory>:/usr/src/app/database -v <yourferdirecipedirectory>:/usr/src/app/recipes -it xthursdayx/ferdi-server-docker
```

There are actually two problems happening here - first, that the npm commands are not able to run with the correct UID/GID settings. The second issue is that the init script does not seem to be running the commands in the correct directory. The commands `npm i -g @adonisjs/cli`, `npm install`, `adonis migration:run --force`, `adonis key:generate`, and finally `adonis serve --dev` should all be running in the directory `/usr/src/app` which is where the latest version of ferdi-server should have been moved after being downloaded and decompressed. 

Based on your log, it's clear that because you're not in the correct directory the `npm install` command is not running with the proper UID/GID setting and is not installing the necessary dependencies. Then the database is not being migrated, the app key is not being generated and finally the `adonis` command fails, because it has not been installed in the correct location and so the `adonis` command is recognized as a valid command. 

This is what your log should look like, when the commands are run in the proper locations:
[https://privatebin.net/?7e6fe1b162c96044#HbydcdaoX7t9Ej4H4o4t55w9gtuDdkG4VYTkZMjVwUdf](https://privatebin.net/?7e6fe1b162c96044#HbydcdaoX7t9Ej4H4o4t55w9gtuDdkG4VYTkZMjVwUdf)

**Comment by xthursdayx** [comment]
Oh, and the reason that there is no CMD in the Dockerfile is because this container is designed to be managed with S6 overlay. The cont-init.d script `50-config` runs each time the container starts in order to check if the user has changed any of the ENV variables, and updates them accordingly. Everything else is left alone other than AdonisJS being told to serve ferdi-server. 

When I wrote the Dockerfile, I tried a number of different CMD and initialization scripts and found that this way worked best with Ferdi-server.

**Comment by xthursdayx** [comment]
@h3x4d3c1m4l  I've continued to look into this and have found that the issue seems to have been related to running Node in Docker with the version of NPM that was being installed. With NPM:6 
 in Docker UID/GID lookup works on some hosts and not on others. I believe that this has been resolved in later versions of NPM.
See: https://github.com/npm/uid-number/issues/7

I have updated the version of NPM and have also changed the way S6 initializes the application to ensure that it is running with the correct UID/GID.

Please try running it again (if you're still interested) and report back if you're still having issues. Thanks.

**Comment by h3x4d3c1m4l** [comment]
Awesome! I'm definitely still interested, will test tomorrow

**Comment by xthursdayx** [comment]
Great, I look forward to hearing if it works or not. Unfortunately, I haven’t been able to find a way to reproduce the issue on either my workstation or server, so it’s a bit difficult to troubleshoot and I have to rely on other people to try out the fixes...

**Comment by h3x4d3c1m4l** [comment]
It runs!! It now tells me the key must be at least 16 characters long, but that's probably easy to solve..

Thank you :):)

**Comment by xthursdayx** [comment]
Very glad to hear that! I’ll add something to the README about the key length. TBH I didn’t know about that requirement either.
